fig, [ax0,ax1,ax2] = plt.subplots(1,3,figsize=(15,5))

data[data['csmokingQuantile']==0]['OBESITY'].hist(bins=50,ax=ax0)
ax0.set_title('<20% reported currently smoking')
ax0.set_xlabel('Obesity rate %')
data[data['csmokingQuantile']==1]['OBESITY'].hist(bins=50,ax=ax1)
ax1.set_title('Middle 60% report currently smoking')
ax1.set_xlabel('Obesity rate %')
data[data['csmokingQuantile']==2]['OBESITY'].hist(bins=50,ax=ax2)
ax2.set_title('>80% (High % of popultion smokes)')
ax2.set_xlabel('Obesity rate %')
plt.show()